name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - name: Test (jest)
        run: |
          yarn pretest
          yarn test.jest
